/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as RegistrationPendingRouteImport } from './routes/registration.pending'
import { Route as RegistrationCorrectionRouteImport } from './routes/registration.correction'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalAccountRouteImport } from './routes/portal.account'
import { Route as DashboardWorkflowRouteImport } from './routes/dashboard.workflow'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRegistrationsRouteImport } from './routes/dashboard.registrations'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMasterDataRouteImport } from './routes/dashboard.master-data'
import { Route as DashboardContentGovernanceRouteImport } from './routes/dashboard.content-governance'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardBreakGlassRouteImport } from './routes/dashboard.break-glass'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardActivityLogRouteImport } from './routes/dashboard.activity-log'
import { Route as PortalReportsIndexRouteImport } from './routes/portal.reports.index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard.reports.index'
import { Route as DashboardCasesIndexRouteImport } from './routes/dashboard.cases.index'
import { Route as PortalReportsNewRouteImport } from './routes/portal.reports.new'
import { Route as PortalReportsRegistrationNumberRouteImport } from './routes/portal.reports.$registrationNumber'
import { Route as PortalReportsSplatRouteImport } from './routes/portal.reports.$'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard.reports.$id'
import { Route as DashboardRegistrationsIdRouteImport } from './routes/dashboard.registrations.$id'
import { Route as DashboardMasterDataUniversitiesRouteImport } from './routes/dashboard.master-data.universities'
import { Route as DashboardMasterDataStudyProgramsRouteImport } from './routes/dashboard.master-data.study-programs'
import { Route as DashboardMasterDataFacultiesRouteImport } from './routes/dashboard.master-data.faculties'
import { Route as DashboardCasesIdRouteImport } from './routes/dashboard.cases.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const RegistrationPendingRoute = RegistrationPendingRouteImport.update({
  id: '/registration/pending',
  path: '/registration/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationCorrectionRoute = RegistrationCorrectionRouteImport.update({
  id: '/registration/correction',
  path: '/registration/correction',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardWorkflowRoute = DashboardWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationsRoute = DashboardRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMasterDataRoute = DashboardMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentGovernanceRoute =
  DashboardContentGovernanceRouteImport.update({
    id: '/content-governance',
    path: '/content-governance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBreakGlassRoute = DashboardBreakGlassRouteImport.update({
  id: '/break-glass',
  path: '/break-glass',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityLogRoute = DashboardActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalReportsIndexRoute = PortalReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesIndexRoute = DashboardCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalReportsNewRoute = PortalReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportsRegistrationNumberRoute =
  PortalReportsRegistrationNumberRouteImport.update({
    id: '/reports/$registrationNumber',
    path: '/reports/$registrationNumber',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalReportsSplatRoute = PortalReportsSplatRouteImport.update({
  id: '/reports/$',
  path: '/reports/$',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationsIdRoute =
  DashboardRegistrationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardRegistrationsRoute,
  } as any)
const DashboardMasterDataUniversitiesRoute =
  DashboardMasterDataUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => DashboardMasterDataRoute,
  } as any)
const DashboardMasterDataStudyProgramsRoute =
  DashboardMasterDataStudyProgramsRouteImport.update({
    id: '/study-programs',
    path: '/study-programs',
    getParentRoute: () => DashboardMasterDataRoute,
  } as any)
const DashboardMasterDataFacultiesRoute =
  DashboardMasterDataFacultiesRouteImport.update({
    id: '/faculties',
    path: '/faculties',
    getParentRoute: () => DashboardMasterDataRoute,
  } as any)
const DashboardCasesIdRoute = DashboardCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/dashboard/activity-log': typeof DashboardActivityLogRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/break-glass': typeof DashboardBreakGlassRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/content-governance': typeof DashboardContentGovernanceRoute
  '/dashboard/master-data': typeof DashboardMasterDataRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflow': typeof DashboardWorkflowRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/registration/correction': typeof RegistrationCorrectionRoute
  '/registration/pending': typeof RegistrationPendingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/cases/$id': typeof DashboardCasesIdRoute
  '/dashboard/master-data/faculties': typeof DashboardMasterDataFacultiesRoute
  '/dashboard/master-data/study-programs': typeof DashboardMasterDataStudyProgramsRoute
  '/dashboard/master-data/universities': typeof DashboardMasterDataUniversitiesRoute
  '/dashboard/registrations/$id': typeof DashboardRegistrationsIdRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/portal/reports/$': typeof PortalReportsSplatRoute
  '/portal/reports/$registrationNumber': typeof PortalReportsRegistrationNumberRoute
  '/portal/reports/new': typeof PortalReportsNewRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/portal/reports/': typeof PortalReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/dashboard/activity-log': typeof DashboardActivityLogRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/break-glass': typeof DashboardBreakGlassRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/content-governance': typeof DashboardContentGovernanceRoute
  '/dashboard/master-data': typeof DashboardMasterDataRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflow': typeof DashboardWorkflowRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/registration/correction': typeof RegistrationCorrectionRoute
  '/registration/pending': typeof RegistrationPendingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/portal': typeof PortalIndexRoute
  '/dashboard/cases/$id': typeof DashboardCasesIdRoute
  '/dashboard/master-data/faculties': typeof DashboardMasterDataFacultiesRoute
  '/dashboard/master-data/study-programs': typeof DashboardMasterDataStudyProgramsRoute
  '/dashboard/master-data/universities': typeof DashboardMasterDataUniversitiesRoute
  '/dashboard/registrations/$id': typeof DashboardRegistrationsIdRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/portal/reports/$': typeof PortalReportsSplatRoute
  '/portal/reports/$registrationNumber': typeof PortalReportsRegistrationNumberRoute
  '/portal/reports/new': typeof PortalReportsNewRoute
  '/dashboard/cases': typeof DashboardCasesIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/portal/reports': typeof PortalReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/dashboard/activity-log': typeof DashboardActivityLogRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/break-glass': typeof DashboardBreakGlassRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/content-governance': typeof DashboardContentGovernanceRoute
  '/dashboard/master-data': typeof DashboardMasterDataRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflow': typeof DashboardWorkflowRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/registration/correction': typeof RegistrationCorrectionRoute
  '/registration/pending': typeof RegistrationPendingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/cases/$id': typeof DashboardCasesIdRoute
  '/dashboard/master-data/faculties': typeof DashboardMasterDataFacultiesRoute
  '/dashboard/master-data/study-programs': typeof DashboardMasterDataStudyProgramsRoute
  '/dashboard/master-data/universities': typeof DashboardMasterDataUniversitiesRoute
  '/dashboard/registrations/$id': typeof DashboardRegistrationsIdRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/portal/reports/$': typeof PortalReportsSplatRoute
  '/portal/reports/$registrationNumber': typeof PortalReportsRegistrationNumberRoute
  '/portal/reports/new': typeof PortalReportsNewRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/portal/reports/': typeof PortalReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/portal'
    | '/register'
    | '/track'
    | '/dashboard/activity-log'
    | '/dashboard/analytics'
    | '/dashboard/break-glass'
    | '/dashboard/content'
    | '/dashboard/content-governance'
    | '/dashboard/master-data'
    | '/dashboard/notifications'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/workflow'
    | '/portal/account'
    | '/portal/notifications'
    | '/registration/correction'
    | '/registration/pending'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/cases/$id'
    | '/dashboard/master-data/faculties'
    | '/dashboard/master-data/study-programs'
    | '/dashboard/master-data/universities'
    | '/dashboard/registrations/$id'
    | '/dashboard/reports/$id'
    | '/portal/reports/$'
    | '/portal/reports/$registrationNumber'
    | '/portal/reports/new'
    | '/dashboard/cases/'
    | '/dashboard/reports/'
    | '/portal/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/track'
    | '/dashboard/activity-log'
    | '/dashboard/analytics'
    | '/dashboard/break-glass'
    | '/dashboard/content'
    | '/dashboard/content-governance'
    | '/dashboard/master-data'
    | '/dashboard/notifications'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/workflow'
    | '/portal/account'
    | '/portal/notifications'
    | '/registration/correction'
    | '/registration/pending'
    | '/dashboard'
    | '/portal'
    | '/dashboard/cases/$id'
    | '/dashboard/master-data/faculties'
    | '/dashboard/master-data/study-programs'
    | '/dashboard/master-data/universities'
    | '/dashboard/registrations/$id'
    | '/dashboard/reports/$id'
    | '/portal/reports/$'
    | '/portal/reports/$registrationNumber'
    | '/portal/reports/new'
    | '/dashboard/cases'
    | '/dashboard/reports'
    | '/portal/reports'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/portal'
    | '/register'
    | '/track'
    | '/dashboard/activity-log'
    | '/dashboard/analytics'
    | '/dashboard/break-glass'
    | '/dashboard/content'
    | '/dashboard/content-governance'
    | '/dashboard/master-data'
    | '/dashboard/notifications'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/workflow'
    | '/portal/account'
    | '/portal/notifications'
    | '/registration/correction'
    | '/registration/pending'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/cases/$id'
    | '/dashboard/master-data/faculties'
    | '/dashboard/master-data/study-programs'
    | '/dashboard/master-data/universities'
    | '/dashboard/registrations/$id'
    | '/dashboard/reports/$id'
    | '/portal/reports/$'
    | '/portal/reports/$registrationNumber'
    | '/portal/reports/new'
    | '/dashboard/cases/'
    | '/dashboard/reports/'
    | '/portal/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  TrackRoute: typeof TrackRoute
  RegistrationCorrectionRoute: typeof RegistrationCorrectionRoute
  RegistrationPendingRoute: typeof RegistrationPendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/registration/pending': {
      id: '/registration/pending'
      path: '/registration/pending'
      fullPath: '/registration/pending'
      preLoaderRoute: typeof RegistrationPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/correction': {
      id: '/registration/correction'
      path: '/registration/correction'
      fullPath: '/registration/correction'
      preLoaderRoute: typeof RegistrationCorrectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/workflow': {
      id: '/dashboard/workflow'
      path: '/workflow'
      fullPath: '/dashboard/workflow'
      preLoaderRoute: typeof DashboardWorkflowRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registrations': {
      id: '/dashboard/registrations'
      path: '/registrations'
      fullPath: '/dashboard/registrations'
      preLoaderRoute: typeof DashboardRegistrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/master-data': {
      id: '/dashboard/master-data'
      path: '/master-data'
      fullPath: '/dashboard/master-data'
      preLoaderRoute: typeof DashboardMasterDataRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content-governance': {
      id: '/dashboard/content-governance'
      path: '/content-governance'
      fullPath: '/dashboard/content-governance'
      preLoaderRoute: typeof DashboardContentGovernanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/break-glass': {
      id: '/dashboard/break-glass'
      path: '/break-glass'
      fullPath: '/dashboard/break-glass'
      preLoaderRoute: typeof DashboardBreakGlassRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity-log': {
      id: '/dashboard/activity-log'
      path: '/activity-log'
      fullPath: '/dashboard/activity-log'
      preLoaderRoute: typeof DashboardActivityLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/reports/': {
      id: '/portal/reports/'
      path: '/reports'
      fullPath: '/portal/reports/'
      preLoaderRoute: typeof PortalReportsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases/': {
      id: '/dashboard/cases/'
      path: '/cases'
      fullPath: '/dashboard/cases/'
      preLoaderRoute: typeof DashboardCasesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/reports/new': {
      id: '/portal/reports/new'
      path: '/reports/new'
      fullPath: '/portal/reports/new'
      preLoaderRoute: typeof PortalReportsNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/$registrationNumber': {
      id: '/portal/reports/$registrationNumber'
      path: '/reports/$registrationNumber'
      fullPath: '/portal/reports/$registrationNumber'
      preLoaderRoute: typeof PortalReportsRegistrationNumberRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/$': {
      id: '/portal/reports/$'
      path: '/reports/$'
      fullPath: '/portal/reports/$'
      preLoaderRoute: typeof PortalReportsSplatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/reports/$id': {
      id: '/dashboard/reports/$id'
      path: '/reports/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registrations/$id': {
      id: '/dashboard/registrations/$id'
      path: '/$id'
      fullPath: '/dashboard/registrations/$id'
      preLoaderRoute: typeof DashboardRegistrationsIdRouteImport
      parentRoute: typeof DashboardRegistrationsRoute
    }
    '/dashboard/master-data/universities': {
      id: '/dashboard/master-data/universities'
      path: '/universities'
      fullPath: '/dashboard/master-data/universities'
      preLoaderRoute: typeof DashboardMasterDataUniversitiesRouteImport
      parentRoute: typeof DashboardMasterDataRoute
    }
    '/dashboard/master-data/study-programs': {
      id: '/dashboard/master-data/study-programs'
      path: '/study-programs'
      fullPath: '/dashboard/master-data/study-programs'
      preLoaderRoute: typeof DashboardMasterDataStudyProgramsRouteImport
      parentRoute: typeof DashboardMasterDataRoute
    }
    '/dashboard/master-data/faculties': {
      id: '/dashboard/master-data/faculties'
      path: '/faculties'
      fullPath: '/dashboard/master-data/faculties'
      preLoaderRoute: typeof DashboardMasterDataFacultiesRouteImport
      parentRoute: typeof DashboardMasterDataRoute
    }
    '/dashboard/cases/$id': {
      id: '/dashboard/cases/$id'
      path: '/cases/$id'
      fullPath: '/dashboard/cases/$id'
      preLoaderRoute: typeof DashboardCasesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardMasterDataRouteChildren {
  DashboardMasterDataFacultiesRoute: typeof DashboardMasterDataFacultiesRoute
  DashboardMasterDataStudyProgramsRoute: typeof DashboardMasterDataStudyProgramsRoute
  DashboardMasterDataUniversitiesRoute: typeof DashboardMasterDataUniversitiesRoute
}

const DashboardMasterDataRouteChildren: DashboardMasterDataRouteChildren = {
  DashboardMasterDataFacultiesRoute: DashboardMasterDataFacultiesRoute,
  DashboardMasterDataStudyProgramsRoute: DashboardMasterDataStudyProgramsRoute,
  DashboardMasterDataUniversitiesRoute: DashboardMasterDataUniversitiesRoute,
}

const DashboardMasterDataRouteWithChildren =
  DashboardMasterDataRoute._addFileChildren(DashboardMasterDataRouteChildren)

interface DashboardRegistrationsRouteChildren {
  DashboardRegistrationsIdRoute: typeof DashboardRegistrationsIdRoute
}

const DashboardRegistrationsRouteChildren: DashboardRegistrationsRouteChildren =
  {
    DashboardRegistrationsIdRoute: DashboardRegistrationsIdRoute,
  }

const DashboardRegistrationsRouteWithChildren =
  DashboardRegistrationsRoute._addFileChildren(
    DashboardRegistrationsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardActivityLogRoute: typeof DashboardActivityLogRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBreakGlassRoute: typeof DashboardBreakGlassRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardContentGovernanceRoute: typeof DashboardContentGovernanceRoute
  DashboardMasterDataRoute: typeof DashboardMasterDataRouteWithChildren
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardRegistrationsRoute: typeof DashboardRegistrationsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWorkflowRoute: typeof DashboardWorkflowRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCasesIdRoute: typeof DashboardCasesIdRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRoute
  DashboardCasesIndexRoute: typeof DashboardCasesIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityLogRoute: DashboardActivityLogRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBreakGlassRoute: DashboardBreakGlassRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardContentGovernanceRoute: DashboardContentGovernanceRoute,
  DashboardMasterDataRoute: DashboardMasterDataRouteWithChildren,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardRegistrationsRoute: DashboardRegistrationsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWorkflowRoute: DashboardWorkflowRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCasesIdRoute: DashboardCasesIdRoute,
  DashboardReportsIdRoute: DashboardReportsIdRoute,
  DashboardCasesIndexRoute: DashboardCasesIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PortalRouteChildren {
  PortalAccountRoute: typeof PortalAccountRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalReportsSplatRoute: typeof PortalReportsSplatRoute
  PortalReportsRegistrationNumberRoute: typeof PortalReportsRegistrationNumberRoute
  PortalReportsNewRoute: typeof PortalReportsNewRoute
  PortalReportsIndexRoute: typeof PortalReportsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountRoute: PortalAccountRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalReportsSplatRoute: PortalReportsSplatRoute,
  PortalReportsRegistrationNumberRoute: PortalReportsRegistrationNumberRoute,
  PortalReportsNewRoute: PortalReportsNewRoute,
  PortalReportsIndexRoute: PortalReportsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  TrackRoute: TrackRoute,
  RegistrationCorrectionRoute: RegistrationCorrectionRoute,
  RegistrationPendingRoute: RegistrationPendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
