/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalAccountRouteImport } from './routes/portal.account'
import { Route as DashboardWorkflowRouteImport } from './routes/dashboard.workflow'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as PortalReportsIndexRouteImport } from './routes/portal.reports.index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard.reports.index'
import { Route as DashboardCasesIndexRouteImport } from './routes/dashboard.cases.index'
import { Route as PortalReportsRegistrationNumberRouteImport } from './routes/portal.reports.$registrationNumber'
import { Route as PortalReportsSplatRouteImport } from './routes/portal.reports.$'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard.reports.$id'
import { Route as DashboardCasesIdRouteImport } from './routes/dashboard.cases.$id'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardWorkflowRoute = DashboardWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalReportsIndexRoute = PortalReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesIndexRoute = DashboardCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalReportsRegistrationNumberRoute =
  PortalReportsRegistrationNumberRouteImport.update({
    id: '/reports/$registrationNumber',
    path: '/reports/$registrationNumber',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalReportsSplatRoute = PortalReportsSplatRouteImport.update({
  id: '/reports/$',
  path: '/reports/$',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesIdRoute = DashboardCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflow': typeof DashboardWorkflowRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/cases/$id': typeof DashboardCasesIdRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/portal/reports/$': typeof PortalReportsSplatRoute
  '/portal/reports/$registrationNumber': typeof PortalReportsRegistrationNumberRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/portal/reports/': typeof PortalReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflow': typeof DashboardWorkflowRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/portal': typeof PortalIndexRoute
  '/dashboard/cases/$id': typeof DashboardCasesIdRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/portal/reports/$': typeof PortalReportsSplatRoute
  '/portal/reports/$registrationNumber': typeof PortalReportsRegistrationNumberRoute
  '/dashboard/cases': typeof DashboardCasesIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/portal/reports': typeof PortalReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflow': typeof DashboardWorkflowRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/cases/$id': typeof DashboardCasesIdRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/portal/reports/$': typeof PortalReportsSplatRoute
  '/portal/reports/$registrationNumber': typeof PortalReportsRegistrationNumberRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/portal/reports/': typeof PortalReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/portal'
    | '/dashboard/analytics'
    | '/dashboard/content'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/workflow'
    | '/portal/account'
    | '/portal/notifications'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/cases/$id'
    | '/dashboard/reports/$id'
    | '/portal/reports/$'
    | '/portal/reports/$registrationNumber'
    | '/dashboard/cases/'
    | '/dashboard/reports/'
    | '/portal/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/content'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/workflow'
    | '/portal/account'
    | '/portal/notifications'
    | '/dashboard'
    | '/portal'
    | '/dashboard/cases/$id'
    | '/dashboard/reports/$id'
    | '/portal/reports/$'
    | '/portal/reports/$registrationNumber'
    | '/dashboard/cases'
    | '/dashboard/reports'
    | '/portal/reports'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/portal'
    | '/dashboard/analytics'
    | '/dashboard/content'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/workflow'
    | '/portal/account'
    | '/portal/notifications'
    | '/dashboard/'
    | '/portal/'
    | '/dashboard/cases/$id'
    | '/dashboard/reports/$id'
    | '/portal/reports/$'
    | '/portal/reports/$registrationNumber'
    | '/dashboard/cases/'
    | '/dashboard/reports/'
    | '/portal/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/workflow': {
      id: '/dashboard/workflow'
      path: '/workflow'
      fullPath: '/dashboard/workflow'
      preLoaderRoute: typeof DashboardWorkflowRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/reports/': {
      id: '/portal/reports/'
      path: '/reports'
      fullPath: '/portal/reports/'
      preLoaderRoute: typeof PortalReportsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases/': {
      id: '/dashboard/cases/'
      path: '/cases'
      fullPath: '/dashboard/cases/'
      preLoaderRoute: typeof DashboardCasesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/portal/reports/$registrationNumber': {
      id: '/portal/reports/$registrationNumber'
      path: '/reports/$registrationNumber'
      fullPath: '/portal/reports/$registrationNumber'
      preLoaderRoute: typeof PortalReportsRegistrationNumberRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/$': {
      id: '/portal/reports/$'
      path: '/reports/$'
      fullPath: '/portal/reports/$'
      preLoaderRoute: typeof PortalReportsSplatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/dashboard/reports/$id': {
      id: '/dashboard/reports/$id'
      path: '/reports/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases/$id': {
      id: '/dashboard/cases/$id'
      path: '/cases/$id'
      fullPath: '/dashboard/cases/$id'
      preLoaderRoute: typeof DashboardCasesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWorkflowRoute: typeof DashboardWorkflowRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCasesIdRoute: typeof DashboardCasesIdRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRoute
  DashboardCasesIndexRoute: typeof DashboardCasesIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWorkflowRoute: DashboardWorkflowRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCasesIdRoute: DashboardCasesIdRoute,
  DashboardReportsIdRoute: DashboardReportsIdRoute,
  DashboardCasesIndexRoute: DashboardCasesIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PortalRouteChildren {
  PortalAccountRoute: typeof PortalAccountRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalReportsSplatRoute: typeof PortalReportsSplatRoute
  PortalReportsRegistrationNumberRoute: typeof PortalReportsRegistrationNumberRoute
  PortalReportsIndexRoute: typeof PortalReportsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountRoute: PortalAccountRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalReportsSplatRoute: PortalReportsSplatRoute,
  PortalReportsRegistrationNumberRoute: PortalReportsRegistrationNumberRoute,
  PortalReportsIndexRoute: PortalReportsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
