import type { TFunction } from "i18next";

const TITLE_RULES: ReadonlyArray<readonly [RegExp, string]> = [
  [/^\/dashboard\/report-withdrawals\//, "withdrawalDetail"],
  [/^\/dashboard\/report-withdrawals$/, "withdrawals"],
  [/^\/dashboard\/information-center\/education\//, "educationArticle"],
  [/^\/dashboard\/information-center\/policies\//, "policyArticle"],
  [/^\/dashboard\/information-center\/education$/, "education"],
  [/^\/dashboard\/information-center\/policies$/, "policies"],
  [/^\/dashboard\/information-center\/faq$/, "faq"],
  [/^\/dashboard\/information-center\/consultation$/, "consultation"],
  [/^\/dashboard\/information-center$/, "informationCenter"],
  [/^\/dashboard\/master-data\/universities\//, "universityDetail"],
  [/^\/dashboard\/master-data\/universities$/, "universities"],
  [/^\/dashboard\/master-data\/faculties$/, "faculties"],
  [/^\/dashboard\/master-data\/study-programs$/, "studyPrograms"],
  [/^\/dashboard\/master-data$/, "masterData"],
  [/^\/dashboard\/registrations\//, "registrationDetail"],
  [/^\/dashboard\/registrations$/, "registrations"],
  [/^\/dashboard\/content-governance$/, "contentGovernance"],
  [/^\/dashboard\/content$/, "contentManagement"],
  [/^\/dashboard\/staff$/, "staffManagement"],
  [/^\/dashboard\/users$/, "users"],
  [/^\/dashboard\/notifications$/, "notifications"],
  [/^\/dashboard\/cases\//, "caseDetail"],
  [/^\/dashboard\/cases$/, "cases"],
  [/^\/dashboard\/reports\//, "reportDetail"],
  [/^\/dashboard\/reports$/, "reports"],
  [/^\/dashboard\/analytics$/, "analytics"],
  [/^\/dashboard\/activity-log$/, "activityLog"],
  [/^\/dashboard\/workflow$/, "workflow"],
  [/^\/dashboard\/settings$/, "settings"],
  [/^\/dashboard\/break-glass$/, "emergencyAccess"],
  [/^\/dashboard$/, "dashboard"],
  [/^\/portal\/reports\/new$/, "newReport"],
  [/^\/portal\/reports\//, "portalReportDetail"],
  [/^\/portal\/reports$/, "portalReports"],
  [/^\/portal\/information-center\/education\//, "educationArticle"],
  [/^\/portal\/information-center\/policies\//, "policyArticle"],
  [/^\/portal\/information-center\/education$/, "education"],
  [/^\/portal\/information-center\/policies$/, "policies"],
  [/^\/portal\/information-center\/faq$/, "faq"],
  [/^\/portal\/information-center\/consultation$/, "consultation"],
  [/^\/portal\/information-center$/, "informationCenter"],
  [/^\/portal\/account$/, "account"],
  [/^\/portal\/notifications$/, "notifications"],
  [/^\/portal$/, "portal"],
  [/^\/login$/, "login"],
  [/^\/register$/, "register"],
  [/^\/registration\/correction$/, "registrationCorrection"],
  [/^\/registration\/pending$/, "registrationPending"],
  [/^\/information-center\/education\//, "educationArticle"],
  [/^\/information-center\/policies\//, "policyArticle"],
  [/^\/information-center\/education$/, "education"],
  [/^\/information-center\/policies$/, "policies"],
  [/^\/information-center\/faq$/, "faq"],
  [/^\/information-center\/consultation$/, "consultation"],
  [/^\/information-center/, "informationCenter"],
  [/^\/track$/, "tracking"],
];

export function localizedDocumentTitle(t: TFunction, pathname: string) {
  const key = TITLE_RULES.find(([pattern]) => pattern.test(pathname))?.[1];

  return key ? `${t(`pageTitles.${key}`)} - SILAPPKASAL` : "SILAPPKASAL";
}
