<?php

return [
    'sections' => [
        ['code' => 'education', 'label_id' => 'Edukasi', 'label_en' => 'Education', 'description' => 'Materi edukasi yang telah melalui proses editorial.', 'display_order' => 10],
        ['code' => 'policy', 'label_id' => 'Seputar Kebijakan', 'label_en' => 'Policy Information', 'description' => 'Informasi kebijakan yang telah diverifikasi.', 'display_order' => 20],
        ['code' => 'faq', 'label_id' => 'FAQ', 'label_en' => 'FAQ', 'description' => 'Pertanyaan dan jawaban yang telah ditinjau.', 'display_order' => 30],
        ['code' => 'consultation', 'label_id' => 'Konsultasi', 'label_en' => 'Consultation', 'description' => 'Kontak layanan institusional yang telah diverifikasi.', 'display_order' => 40],
    ],

    'categories' => [
        ['section' => 'education', 'code' => 'perspective_islam', 'name' => 'Perspektif Islam', 'icon' => 'book-open', 'description' => 'Materi edukasi berbasis sumber keislaman yang telah diverifikasi dan ditinjau.'],
        ['section' => 'education', 'code' => 'perspective_psychology', 'name' => 'Perspektif Psikolog', 'icon' => 'brain', 'description' => 'Pengetahuan umum tentang respons psikologis, batasan diri, komunikasi, dan dukungan.'],
        ['section' => 'education', 'code' => 'perspective_law', 'name' => 'Perspektif Hukum', 'icon' => 'scale', 'description' => 'Informasi hukum umum yang membantu pembaca memahami hak dan jalur bantuan.'],
        ['section' => 'education', 'code' => 'perspective_sociocultural', 'name' => 'Perspektif Sosial Budaya', 'icon' => 'users', 'description' => 'Edukasi mengenai pengaruh norma, stigma, komunitas, dan perubahan budaya.'],
        ['section' => 'education', 'code' => 'speak_up', 'name' => 'Ayo Speak Up!', 'icon' => 'megaphone', 'description' => 'Panduan umum untuk mengenali situasi dan mencari jalur pelaporan yang tepat.'],
        ['section' => 'education', 'code' => 'stop_sexual_violence', 'name' => 'STOP Kekerasan Seksual!', 'icon' => 'shield', 'description' => 'Materi pencegahan dan respons awal yang aman terhadap kekerasan seksual.'],
        ['section' => 'education', 'code' => 'you_are_not_alone', 'name' => 'Kamu Tidak Sendiri', 'icon' => 'heart-hand', 'description' => 'Materi dukungan yang menegaskan pilihan bantuan tanpa menjanjikan hasil tertentu.'],
        ['section' => 'education', 'code' => 'understand_reporting_flow', 'name' => 'Pahami Alur Pelaporanmu!', 'icon' => 'signpost', 'description' => 'Informasi umum untuk mempersiapkan dan memahami pelaporan di lingkungan kampus.'],
        ['section' => 'policy', 'code' => 'legislation', 'name' => 'Perundang-undangan', 'icon' => 'landmark', 'description' => 'Ringkasan edukatif mengenai regulasi yang telah diverifikasi dan masih berlaku.'],
        ['section' => 'policy', 'code' => 'higher_education_policy', 'name' => 'Kebijakan Perguruan Tinggi', 'icon' => 'university', 'description' => 'Informasi kebijakan perguruan tinggi yang telah ditinjau dan disetujui untuk publikasi.'],
    ],

    'articles' => [
        ['perspective_islam_quran_verses', 'Ayat Al-Qur’an', 'perspective_islam'],
        ['perspective_islam_hadith', 'Hadis', 'perspective_islam'],
        ['perspective_islam_inspirational_stories', 'Kisah Inspiratif', 'perspective_islam'],
        ['perspective_islam_scholar_views', 'Kata Ulama', 'perspective_islam'],
        ['perspective_psychology_myths_facts', 'Mitos vs Fakta tentang Kekerasan Seksual', 'perspective_psychology'],
        ['perspective_psychology_warning_signs', 'Mengenali Tanda Bahaya', 'perspective_psychology'],
        ['perspective_psychology_personal_boundaries', 'Membangun Batasan Diri', 'perspective_psychology'],
        ['perspective_psychology_assertive_communication', 'Komunikasi Asertif', 'perspective_psychology'],
        ['perspective_psychology_friends_community_role', 'Peran Teman dan Komunitas', 'perspective_psychology'],
        ['perspective_psychology_gaslighting_manipulation', 'Mengenali Gaslighting dan Manipulasi', 'perspective_psychology'],
        ['perspective_law_forms', 'Mengenali Bentuk Kekerasan Seksual dalam Hukum', 'perspective_law'],
        ['perspective_law_victim_rights', 'Hak-Hak Korban dalam Perspektif Hukum', 'perspective_law'],
        ['perspective_law_available_steps', 'Langkah Hukum yang Bisa Ditempuh', 'perspective_law'],
        ['perspective_law_perpetrator_sanctions', 'Sanksi Hukum bagi Pelaku', 'perspective_law'],
        ['perspective_law_legal_aid_support', 'Bantuan Hukum dan Lembaga Pendukung', 'perspective_law'],
        ['perspective_law_prevention_through_policy', 'Pencegahan Kekerasan Seksual melalui Kebijakan Hukum', 'perspective_law'],
        ['perspective_sociocultural_social_norms', 'Norma Sosial dan Kekerasan Seksual', 'perspective_sociocultural'],
        ['perspective_sociocultural_patriarchy_impact', 'Budaya Patriarki dan Dampaknya', 'perspective_sociocultural'],
        ['perspective_sociocultural_community_prevention_role', 'Peran Masyarakat dalam Pencegahan', 'perspective_sociocultural'],
        ['perspective_sociocultural_victim_stigma', 'Stigma terhadap Korban', 'perspective_sociocultural'],
        ['perspective_sociocultural_campaigns_movements', 'Kampanye dan Gerakan Sosial', 'perspective_sociocultural'],
        ['perspective_sociocultural_culture_change_safe_campus', 'Perubahan Budaya untuk Kampus Aman', 'perspective_sociocultural'],
        ['speak_up_reportable_situations', 'Mengenali Situasi yang Harus Dilaporkan', 'speak_up'],
        ['speak_up_how_to_speak', 'Bagaimana Cara Berani Bicara?', 'speak_up'],
        ['speak_up_where_to_report', 'Ke Mana Harus Melapor?', 'speak_up'],
        ['speak_up_myths_facts', 'Mitos vs Fakta tentang Speak Up', 'speak_up'],
        ['speak_up_building_culture', 'Bersama Membangun Budaya Speak Up', 'speak_up'],
        ['stop_sexual_violence_why_stop', 'Mengapa Harus Dihentikan?', 'stop_sexual_violence'],
        ['stop_sexual_violence_prevention_steps', 'Langkah-Langkah Pencegahan', 'stop_sexual_violence'],
        ['stop_sexual_violence_when_you_or_friend_affected', 'Jika Kamu atau Temanmu Mengalami Kekerasan Seksual', 'stop_sexual_violence'],
        ['stop_sexual_violence_together_we_can_stop', 'Bersama, Kita Bisa Menghentikan Kekerasan Seksual!', 'stop_sexual_violence'],
        ['you_are_not_alone_why', 'Mengapa Kamu Tidak Sendiri?', 'you_are_not_alone'],
        ['you_are_not_alone_find_support', 'Temukan Dukungan di Sekitarmu', 'you_are_not_alone'],
        ['you_are_not_alone_recovery_steps', 'Langkah untuk Memulihkan Diri', 'you_are_not_alone'],
        ['you_are_not_alone_recovery_testimonial', 'Testimoni: Mereka Berhasil Bangkit', 'you_are_not_alone'],
        ['you_are_not_alone_build_safe_environment', 'Bersama Membangun Lingkungan Aman', 'you_are_not_alone'],
        ['understand_reporting_flow_prepare_self_evidence', 'Langkah Awal: Siapkan Diri dan Bukti', 'understand_reporting_flow'],
        ['understand_reporting_flow_where_to_report', 'Ke Mana Harus Melapor?', 'understand_reporting_flow'],
        ['understand_reporting_flow_campus_reporting_flow', 'Alur Pelaporan di Kampus', 'understand_reporting_flow'],
        ['understand_reporting_flow_rights_to_know', 'Hak-Hak yang Harus Kamu Ketahui', 'understand_reporting_flow'],
        ['understand_reporting_flow_do_not_be_afraid', 'Jangan Takut, Kamu Tidak Sendiri!', 'understand_reporting_flow'],
    ],

    'faqs' => [
        'Apakah identitas pelapor aman?',
        'Siapa yang dapat melihat laporan saya?',
        'Apa perbedaan laporan terbuka, rahasia, dan anonim?',
        'Apa yang perlu dipersiapkan sebelum membuat laporan?',
        'Bagaimana proses penanganan laporan?',
        'Bagaimana cara menghubungi PPKS?',
        'Apakah saya dapat melihat progres laporan?',
        'Apakah bukti tambahan dapat dikirim setelah laporan dibuat?',
    ],
];
